# Generated by Django 3.1.5 on 2021-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('keyskills', models.CharField(max_length=100)),
                ('exprience', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=252)),
                ('designation', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=50)),
                ('e_date', models.DateField()),
                ('p_date', models.DateField()),
            ],
            options={
                'db_table': 'job_openings',
                'managed': False,
            },
        ),
    ]
