# Generated by Django 3.1.5 on 2021-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0002_jobopenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'key_skills',
                'managed': False,
            },
        ),
    ]
