# Generated by Django 3.1.5 on 2021-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0003_keyskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'area_of_sectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_passing', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_cgpa', models.FloatField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('area_of_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('exp', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_vacancies', models.IntegerField(blank=True, null=True)),
                ('lasr_date_application', models.CharField(blank=True, max_length=50, null=True)),
                ('hiring_process', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('r_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_count', models.CharField(max_length=20)),
                ('post_date', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(max_length=50)),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('job_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('written_test', models.CharField(max_length=10)),
                ('group_discussion', models.CharField(max_length=10)),
                ('technical_round', models.CharField(max_length=10)),
                ('hr_round', models.CharField(max_length=10)),
                ('meta_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'job_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'job_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpApplayJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('s_email', models.CharField(blank=True, max_length=150, null=True)),
                ('r_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jp_applay_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpContectUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mno', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jp_contect_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpFavJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('s_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jp_fav_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jp_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat_rating', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('seeker_email', models.TextField(blank=True, null=True)),
                ('recruiter_email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jp_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mno', models.CharField(blank=True, max_length=20, null=True)),
                ('ps', models.CharField(blank=True, max_length=50, null=True)),
                ('org_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.CharField(blank=True, max_length=250, null=True)),
                ('veri', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('pay', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('show_on_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('pay_count', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal', models.TextField(blank=True, null=True)),
                ('counter', models.CharField(max_length=50)),
                ('google_id', models.TextField(blank=True, null=True)),
                ('job_count', models.IntegerField()),
            ],
            options={
                'db_table': 'recruiter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ps', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.CharField(blank=True, max_length=250, null=True)),
                ('p_locaion', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('qua', models.CharField(blank=True, max_length=50, null=True)),
                ('p_year', models.CharField(blank=True, max_length=20, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('aofs', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.CharField(blank=True, max_length=250, null=True)),
                ('veri', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('counter', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('google_id', models.TextField(blank=True, null=True)),
                ('plan', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=50)),
                ('pay_date', models.CharField(max_length=50)),
                ('paypal', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('show_on_reg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seeker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
    ]
