# Generated by Django 3.1.5 on 2021-02-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0004_areaofsectors_designation_experience_jobpost_jobrole_jobtypes_jpapplayjob_jpcontectus_jpfavjob_jpnot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobpost',
            table=None,
        ),
    ]
