# Generated by Django 3.1.5 on 2021-02-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0005_auto_20210205_1048'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobpost',
            table='job_post',
        ),
    ]
