# Generated by Django 3.1.5 on 2021-02-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0006_auto_20210205_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='JobOpenings',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.DeleteModel(
            name='JobTypes',
        ),
        migrations.DeleteModel(
            name='JpApplayJob',
        ),
        migrations.DeleteModel(
            name='JpContectUs',
        ),
        migrations.DeleteModel(
            name='JpFavJob',
        ),
        migrations.DeleteModel(
            name='JpNotification',
        ),
        migrations.DeleteModel(
            name='JpReview',
        ),
        migrations.DeleteModel(
            name='KeySkills',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.DeleteModel(
            name='Seeker',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterModelTable(
            name='areaofsectors',
            table=None,
        ),
    ]
