# Generated by Django 3.1.5 on 2021-02-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontlayout', '0007_auto_20210205_1141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areaofsectors',
            table='area_of_sectors',
        ),
    ]
