# Generated by Django 3.1.5 on 2021-02-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'area_of_sectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=252)),
                ('salary_range', models.CharField(max_length=50)),
                ('e_date', models.DateField()),
                ('p_date', models.DateField()),
            ],
            options={
                'db_table': 'job_openings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_passing', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_cgpa', models.FloatField(blank=True, null=True)),
                ('number_of_vacancies', models.IntegerField(blank=True, null=True)),
                ('lasr_date_application', models.DateField()),
                ('hiring_process', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('pay_count', models.CharField(max_length=20)),
                ('post_date', models.DateField()),
                ('application', models.CharField(max_length=50)),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('job_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('written_test', models.CharField(max_length=10)),
                ('group_discussion', models.CharField(max_length=10)),
                ('technical_round', models.CharField(max_length=10)),
                ('hr_round', models.CharField(max_length=10)),
                ('meta_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'job_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'job_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpApplayJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('s_email', models.CharField(blank=True, max_length=150, null=True)),
                ('r_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jp_applay_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpContectUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mno', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jp_contect_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpFavJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('s_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jp_fav_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jp_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JpReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat_rating', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('seeker_email', models.TextField(blank=True, null=True)),
                ('recruiter_email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jp_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'key_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mno', models.CharField(blank=True, max_length=20, null=True)),
                ('ps', models.CharField(blank=True, max_length=50, null=True)),
                ('org_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.CharField(blank=True, max_length=250, null=True)),
                ('veri', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('pay', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('show_on_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('pay_count', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal', models.TextField(blank=True, null=True)),
                ('counter', models.CharField(max_length=50)),
                ('google_id', models.TextField(blank=True, null=True)),
                ('job_count', models.IntegerField()),
            ],
            options={
                'db_table': 'recruiter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('mno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('current_address', models.CharField(blank=True, max_length=250, null=True)),
                ('p_year', models.CharField(blank=True, max_length=20, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'seeker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('c_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='testimonials')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'testimonials',
                'managed': False,
            },
        ),
    ]
